package com.macsof.domain;

// Generated Apr 15, 2015 7:06:38 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "tracker")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private String cname;
	private String phone;
	private String enqCode;
	private String demo;
	private Date date;
	private String address;
	private String enqFor;
	private Set<Tracking> trackings = new TreeSet<Tracking>();

	public Customer() {
	}

	public Customer(String phone) {
		this.phone = phone;
	}

	public Customer(String cname, String phone, String enqCode, String demo,
			Date date, String address, Set<Tracking> trackings) {
		this.cname = cname;
		this.phone = phone;
		this.enqCode = enqCode;
		this.demo = demo;
		this.date = date;
		this.address = address;
		this.trackings = trackings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CNAME", length = 45)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Column(name = "PHONE", nullable = false, length = 13)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ENQ_CODE", length = 45)
	public String getEnqCode() {
		return this.enqCode;
	}

	public void setEnqCode(String enqCode) {
		this.enqCode = enqCode;
	}

	@Column(name = "DEMO", length = 3)
	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "ADDRESS", length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	@OrderBy("trackId DESC")
	public Set<Tracking> getTrackings() {
		return this.trackings;
	}

	public void setTrackings(Set<Tracking> trackings) {
		this.trackings = trackings;
	}

	@Column(name = "ENQUIRY_FOR", length = 50)
	public String getEnqFor() {
		return enqFor;
	}

	public void setEnqFor(String enqFor) {
		this.enqFor = enqFor;
	}

}
