package com.macsof.domain;

// Generated Apr 15, 2015 7:06:38 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Installation generated by hbm2java
 */
@Entity
@Table(name = "installation", catalog = "tracker")
public class Installation implements java.io.Serializable {

	private Integer installationId;
	private String technician;
	private Date installationDate;
	private String status;
	private Integer customerId;
	private String note;

	public Installation() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "INSTALLATION_ID", unique = true, nullable = false)
	public Integer getInstallationId() {
		return this.installationId;
	}

	public void setInstallationId(Integer installationId) {
		this.installationId = installationId;
	}

	@Column(name = "TECHNICIAN", length = 35)
	public String getTechnician() {
		return this.technician;
	}

	public void setTechnician(String technician) {
		this.technician = technician;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INSTALLATION_DATE", length = 10)
	public Date getInstallationDate() {
		return this.installationDate;
	}

	public void setInstallationDate(Date installationDate) {
		this.installationDate = installationDate;
	}

	@Column(name = "STATUS", length = 15)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CUSTOMER_ID")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "NOTE", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	

}
